### ISSUE TITLE
Make GitHub releases and keep it synced with PyPI packages

### ISSUE THREAD

**Issue by hsluoyz** [pycasbin/flask-authz#8]
Hi @jessecooper , I have made you the maintainer of this repo (after your acception).

I have made two releases in GitHub: https://github.com/pycasbin/flask-authz/releases . Is this OK?

If the version v2.0.0 is OK, you can release it at the same commit to: PyPI: https://pypi.org/project/flask-authz/

You can tell me your PyPI usernames, so I can give you permissions.

**Comment by hsluoyz** [comment]
@jessecooper btw, are the test cases in this repo still working? I saw two test_xxx.py files but they are not runnable..

![image](https://user-images.githubusercontent.com/3787410/86311444-0034f700-bc53-11ea-8259-425c6ab85744.png)

![image](https://user-images.githubusercontent.com/3787410/86311459-07f49b80-bc53-11ea-95f7-b44aa35491aa.png)

**Comment by jessecooper** [comment]
@hsluoyz If this is pycharm you will need to set the project to use pytest. If you go into your `preferences -> tools -> python integration tools` you can set the default test runner to pytest.

**Comment by jessecooper** [comment]
@hsluoyz The 2.0 release looks good. I will email you the PyPI account names.

**Comment by jessecooper** [comment]
@hsluoyz can you please also add @dfresh613 as a maintainer?

**Comment by hsluoyz** [comment]
@jessecooper if that's the case, why not add `pytest` to the dev dependency? (I saw you add that file).

**Comment by jessecooper** [comment]
@hsluoyz if you look in the `dev_requirements.txt` pytest is in there. There is no need to have an IDE to use pytest. To run the tests from cli ensure you have installed the dev_requirements.txt `pip install -r dev_requirements.txt` and just run `pytest`. If you want to see the coverage just add the `--cov <package_name>` flag to the `pytest` command. The travis file is running the tests with the command `pytest --cov flask_authz`. This seems to all be working properly and uploading the test results to Coveralls.

**Comment by hsluoyz** [comment]
Is `dev_requirements.txt` (the filename) a part of Python or Pip RFC? It is not automatically recognized by PyCharm IDE to prompt me to install the dependencies.

**Comment by jessecooper** [comment]
@hsluoyz good point, I do not believe there is anything in a PEP about the `dev_requirements.txt` name. I have picked it up as a practice after seeing other projects uses it over the years. I didn't want to put everything into requirements.txt because I want to reduce the package dependencies in a production deployment that would not need the dev tools installed. If you look at setup.py it reads in the requirements file to supply the `install_requires` arg. I could do a similar thing with `dev_requirements.txt` and feed it into an extra_require dev key:
```python
    extras_require={
        'dev': dev_requirements
    }
```
This allows the user to install the dev requirements with pip:
`pip install -e .[dev]`. 
I do like using pip-tools to manage requirements files and having that feed into the setup.py file but it is just something I have adopted to manage python package dependencies over the years and I am unsure how IDEs would adapt to that because of it being a non standard style. I personally manage my envs from the CLI so I didn't notice pycharm didn't pick it up. I am definitely opened to suggestions in this area and I will also look at the PEP to see if maybe the requirements.txt file names can be patterned or if there is any specifications around that.

**Comment by dfresh613** [comment]
I don't think `extras_require` is the way to go, that should be reserved for if we want to enable specific extra packages depending on underlying technologies: IE `pip install flask-authz[sqlalchemy]` or `pip install flask-authz[redis]` (just some examples of what extra_require should be used for).

It doesn't make sense to have production installs require all the development linting, testing, and pre-commit tools, which is why the separate dev_requirements.txt makes sense as @jessecooper mentioned.

I can understand @hsluoyz viewpoint as well - how would the end user know those extra requirements are needed to run unit tests.

The resolution for this can be simple - lets update the readme and add a specific section for "unit testing".  I will open a PR with this change, and if you both agree this is sufficient, we can merge.

**Comment by jessecooper** [comment]
@hsluoyz ill push to PyPI after you review the doc update just so it is reflected in both places.

**Comment by hsluoyz** [comment]
@dfresh613 well explained. Thanks!

@jessecooper please go ahead.
